"""Added nyt_review_url field to book class

Revision ID: 0f5bbb6aad3d
Revises: 729d114cacf0
Create Date: 2017-06-01 14:50:20.978543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5bbb6aad3d'
down_revision = '729d114cacf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('nyt_review_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'nyt_review_url')
    # ### end Alembic commands ###
