"""Adding followers/following to users

Revision ID: 729d114cacf0
Revises: 1bac940830fc
Create Date: 2017-05-31 17:37:33.353336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729d114cacf0'
down_revision = '1bac940830fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('follower_id != followee_id', name='no_self_follow'),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
